import { CSSProperties } from 'react';

type Color = 'currentColor' | string;

export interface IconProps {
  color?: Color;
  size?: number | string;
  variant?: 'light' | 'regular' | 'bold' | 'filled';
  style?: CSSProperties;
  title?: string;
  className?: string;
}

// types for weather icons
export const AltArrowDown: React.FC<IconProps>;
export const AltArrowLeft: React.FC<IconProps>;
export const AltArrowRight: React.FC<IconProps>;
export const AltArrowUp: React.FC<IconProps>;
export const ArrowDown: React.FC<IconProps>;
export const ArrowLeft: React.FC<IconProps>;
export const ArrowLeftDown: React.FC<IconProps>;
export const ArrowLeftUp: React.FC<IconProps>;
export const ArrowRight: React.FC<IconProps>;
export const ArrowRightDown: React.FC<IconProps>;
export const ArrowRightUp: React.FC<IconProps>;
export const ArrowUp: React.FC<IconProps>;
export const DoubleAltArrowDown: React.FC<IconProps>;
export const DoubleAltArrowLeft: React.FC<IconProps>;
export const DoubleAltArrowRight: React.FC<IconProps>;
export const DoubleAltArrowUp: React.FC<IconProps>;
export const Refresh: React.FC<IconProps>;
export const RefreshCircle: React.FC<IconProps>;
export const RefreshSquare: React.FC<IconProps>;
export const Restart: React.FC<IconProps>;
export const RestartCircle: React.FC<IconProps>;
export const RestartSquare: React.FC<IconProps>;
export const RoundAltArrowDown: React.FC<IconProps>;
export const RoundAltArrowLeft: React.FC<IconProps>;
export const RoundAltArrowRight: React.FC<IconProps>;
export const RoundAltArrowUp: React.FC<IconProps>;
export const RoundArrowDown: React.FC<IconProps>;
export const RoundArrowLeft: React.FC<IconProps>;
export const RoundArrowLeftDown: React.FC<IconProps>;
export const RoundArrowLeftUp: React.FC<IconProps>;
export const RoundArrowRight: React.FC<IconProps>;
export const RoundArrowRightDown: React.FC<IconProps>;
export const RoundArrowRightUp: React.FC<IconProps>;
export const RoundArrowUp: React.FC<IconProps>;
export const RoundDoubleAltArrowDown: React.FC<IconProps>;
export const RoundDoubleAltArrowLeft: React.FC<IconProps>;
export const RoundDoubleAltArrowRight: React.FC<IconProps>;
export const RoundDoubleAltArrowUp: React.FC<IconProps>;
export const RoundSortHorizontal: React.FC<IconProps>;
export const RoundSortVertical: React.FC<IconProps>;
export const RoundTransferDiagonal: React.FC<IconProps>;
export const RoundTransferHorizontal: React.FC<IconProps>;
export const RoundTransferVertical: React.FC<IconProps>;
export const SortHorizontal: React.FC<IconProps>;
export const SortVertical: React.FC<IconProps>;
export const SquareAltArrowDown: React.FC<IconProps>;
export const SquareAltArrowLeft: React.FC<IconProps>;
export const SquareAltArrowRight: React.FC<IconProps>;
export const SquareAltArrowUp: React.FC<IconProps>;
export const SquareArrowDown: React.FC<IconProps>;
export const SquareArrowLeft: React.FC<IconProps>;
export const SquareArrowLeftDown: React.FC<IconProps>;
export const SquareArrowLeftUp: React.FC<IconProps>;
export const SquareArrowRight: React.FC<IconProps>;
export const SquareArrowRightDown: React.FC<IconProps>;
export const SquareArrowRightUp: React.FC<IconProps>;
export const SquareArrowUp: React.FC<IconProps>;
export const SquareDoubleAltArrowDown: React.FC<IconProps>;
export const SquareDoubleAltArrowLeft: React.FC<IconProps>;
export const SquareDoubleAltArrowRight: React.FC<IconProps>;
export const SquareDoubleAltArrowUp: React.FC<IconProps>;
export const SquareSortHorizontal: React.FC<IconProps>;
export const SquareSortVertical: React.FC<IconProps>;
export const SquareTransferHorizontal: React.FC<IconProps>;
export const SquareTransferVertical: React.FC<IconProps>;
export const TransferHorizontal: React.FC<IconProps>;
export const TransferVertical: React.FC<IconProps>;

// types for notifications icons
export const NotificationUnread: React.FC<IconProps>;
export const NotificationUnreadLines: React.FC<IconProps>;
export const NotificationRemove: React.FC<IconProps>;
export const NotificationLinesRemove: React.FC<IconProps>;
export const Bell: React.FC<IconProps>;
export const BellBing: React.FC<IconProps>;
export const BellOff: React.FC<IconProps>;

// types for documents icons
export const Archive: React.FC<IconProps>;
export const ArchiveCheck: React.FC<IconProps>;
export const ArchiveDown: React.FC<IconProps>;
export const ArchiveDownMinimlistic: React.FC<IconProps>;
export const ArchiveMinimalistic: React.FC<IconProps>;
export const ArchiveUp: React.FC<IconProps>;
export const ArchiveUpMinimlistic: React.FC<IconProps>;
export const Clipboard: React.FC<IconProps>;
export const ClipboardAdd: React.FC<IconProps>;
export const ClipboardCheck: React.FC<IconProps>;
export const ClipboardHeart: React.FC<IconProps>;
export const ClipboardList: React.FC<IconProps>;
export const ClipboardRemove: React.FC<IconProps>;
export const ClipboardText: React.FC<IconProps>;
export const Document: React.FC<IconProps>;
export const DocumentAdd: React.FC<IconProps>;
export const DocumentMedicine: React.FC<IconProps>;
export const Documents: React.FC<IconProps>;
export const DocumentsMinimalistic: React.FC<IconProps>;
export const DocumentText: React.FC<IconProps>;
export const Notebook: React.FC<IconProps>;
export const Notes: React.FC<IconProps>;
export const NotesMinimalistic: React.FC<IconProps>;

// types for weather icons
export const Sun: React.FC<IconProps>;
export const Moon: React.FC<IconProps>;
export const Cloud: React.FC<IconProps>;
export const CloudBolt: React.FC<IconProps>;
export const CloudBoltMinimalistic: React.FC<IconProps>;
export const CloudCheck: React.FC<IconProps>;
export const CloudDownload: React.FC<IconProps>;
export const CloudMinus: React.FC<IconProps>;
export const CloudPlus: React.FC<IconProps>;
export const CloudRain: React.FC<IconProps>;
export const Clouds: React.FC<IconProps>;
export const CloudSnowfall: React.FC<IconProps>;
export const CloudSnowfallMinimalistic: React.FC<IconProps>;
export const CloudStorm: React.FC<IconProps>;
export const CloudSun: React.FC<IconProps>;
export const CloudSun2: React.FC<IconProps>;
export const CloudUpload: React.FC<IconProps>;
export const CloudWaterdrop: React.FC<IconProps>;
export const CloudWaterdrops: React.FC<IconProps>;
export const CloudyMoon: React.FC<IconProps>;
export const CloundCross: React.FC<IconProps>;
export const MoonSleep: React.FC<IconProps>;
export const MoonStars: React.FC<IconProps>;
export const Snowflake: React.FC<IconProps>;
export const Stars: React.FC<IconProps>;
export const Sun2: React.FC<IconProps>;
export const SunFog: React.FC<IconProps>;
export const Sunrise: React.FC<IconProps>;
export const Sunset: React.FC<IconProps>;
export const Temperature: React.FC<IconProps>;
export const Tornado: React.FC<IconProps>;
export const TornadoSmall: React.FC<IconProps>;
export const Waterdrops: React.FC<IconProps>;
export const Wind: React.FC<IconProps>;
